[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn server:app --workers 1 --threads 4 --bind 0.0.0.0:$PORT"
restartPolicyType = "always"

[environments.production.variables]
PYTHONUNBUFFERED = "1"
PROCESS_TYPE = "worker"